version: "3"

services:

  rabbitmq:
    build:
      dockerfile: Dockerfile
      context: ./rabbitmq/
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

    networks:
        - message-broker

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - rabbitmq-prometheus_prometheus:/prometheus
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - message-broker
    depends_on:
      - rabbitmq

  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - "3000:3000"
    networks:
      - message-broker
    volumes:
      - rabbitmq-prometheus_grafana:/var/lib/grafana
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/dashboards:/dashboards
    environment:
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
 
networks: 
  message-broker:
    driver: bridge

volumes:
  rabbitmq-prometheus_prometheus:
  rabbitmq-prometheus_grafana:

